// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu2nYDewTInPQKUvgLhcBZsYWxhe14X9A',
    appId: '1:937635031063:web:1150d69a1fa0214cef9452',
    messagingSenderId: '937635031063',
    projectId: 'ncsproject-f7880',
    authDomain: 'ncsproject-f7880.firebaseapp.com',
    storageBucket: 'ncsproject-f7880.firebasestorage.app',
    measurementId: 'G-11612LJ7BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB0O_H39x0GJKL5LQld5KxVx-jr3hcZbA',
    appId: '1:937635031063:android:449f59278ff8c3a9ef9452',
    messagingSenderId: '937635031063',
    projectId: 'ncsproject-f7880',
    storageBucket: 'ncsproject-f7880.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm9GckYldVNHenUHXYVmtBvJc6QQhI50A',
    appId: '1:937635031063:ios:0eff4398c0664fc7ef9452',
    messagingSenderId: '937635031063',
    projectId: 'ncsproject-f7880',
    storageBucket: 'ncsproject-f7880.firebasestorage.app',
    iosBundleId: 'com.example.ncs',
  );
}
